// <auto-generated />
namespace EventAppMVCPresentationLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PutGuestsinEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PutGuestsinEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191915240_Put Guests in EF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
